/**
 * Sovereign-state metadata keyed by world-atlas numeric id.
 * ~197 entries: 193 UN members + Taiwan, Kosovo, Palestine, Vatican.
 * `aliases` are lowercased, diacritic-free alternate names accepted by the matcher.
 */
export type IsoInfo = {
  name: string
  iso2: string
  iso3: string
  aliases: Array<string>
}

export const ISO_META: Record<string, IsoInfo> = {
  "004": { name: "Afghanistan", iso2: "AF", iso3: "AFG", aliases: [] },
  "008": { name: "Albania", iso2: "AL", iso3: "ALB", aliases: [] },
  "012": { name: "Algeria", iso2: "DZ", iso3: "DZA", aliases: [] },
  "020": { name: "Andorra", iso2: "AD", iso3: "AND", aliases: [] },
  "024": { name: "Angola", iso2: "AO", iso3: "AGO", aliases: [] },
  "028": { name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", aliases: ["antigua and barb.", "antigua"] },
  "032": { name: "Argentina", iso2: "AR", iso3: "ARG", aliases: [] },
  "051": { name: "Armenia", iso2: "AM", iso3: "ARM", aliases: [] },
  "036": { name: "Australia", iso2: "AU", iso3: "AUS", aliases: [] },
  "040": { name: "Austria", iso2: "AT", iso3: "AUT", aliases: [] },
  "031": { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", aliases: [] },
  "044": { name: "Bahamas", iso2: "BS", iso3: "BHS", aliases: ["the bahamas"] },
  "048": { name: "Bahrain", iso2: "BH", iso3: "BHR", aliases: [] },
  "050": { name: "Bangladesh", iso2: "BD", iso3: "BGD", aliases: [] },
  "052": { name: "Barbados", iso2: "BB", iso3: "BRB", aliases: [] },
  "112": { name: "Belarus", iso2: "BY", iso3: "BLR", aliases: [] },
  "056": { name: "Belgium", iso2: "BE", iso3: "BEL", aliases: [] },
  "084": { name: "Belize", iso2: "BZ", iso3: "BLZ", aliases: [] },
  "204": { name: "Benin", iso2: "BJ", iso3: "BEN", aliases: [] },
  "064": { name: "Bhutan", iso2: "BT", iso3: "BTN", aliases: [] },
  "068": { name: "Bolivia", iso2: "BO", iso3: "BOL", aliases: [] },
  "070": { name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", aliases: ["bosnia and herz.", "bosnia"] },
  "072": { name: "Botswana", iso2: "BW", iso3: "BWA", aliases: [] },
  "076": { name: "Brazil", iso2: "BR", iso3: "BRA", aliases: [] },
  "096": { name: "Brunei", iso2: "BN", iso3: "BRN", aliases: ["brunei darussalam"] },
  "100": { name: "Bulgaria", iso2: "BG", iso3: "BGR", aliases: [] },
  "854": { name: "Burkina Faso", iso2: "BF", iso3: "BFA", aliases: [] },
  "108": { name: "Burundi", iso2: "BI", iso3: "BDI", aliases: [] },
  "132": { name: "Cabo Verde", iso2: "CV", iso3: "CPV", aliases: ["cape verde"] },
  "116": { name: "Cambodia", iso2: "KH", iso3: "KHM", aliases: [] },
  "120": { name: "Cameroon", iso2: "CM", iso3: "CMR", aliases: [] },
  "124": { name: "Canada", iso2: "CA", iso3: "CAN", aliases: [] },
  "140": { name: "Central African Republic", iso2: "CF", iso3: "CAF", aliases: ["central african rep.", "car"] },
  "148": { name: "Chad", iso2: "TD", iso3: "TCD", aliases: [] },
  "152": { name: "Chile", iso2: "CL", iso3: "CHL", aliases: [] },
  "156": { name: "China", iso2: "CN", iso3: "CHN", aliases: ["prc", "peoples republic of china"] },
  "170": { name: "Colombia", iso2: "CO", iso3: "COL", aliases: [] },
  "174": { name: "Comoros", iso2: "KM", iso3: "COM", aliases: [] },
  "178": { name: "Republic of the Congo", iso2: "CG", iso3: "COG", aliases: ["congo", "congo-brazzaville"] },
  "180": { name: "Democratic Republic of the Congo", iso2: "CD", iso3: "COD", aliases: ["dem. rep. congo", "drc", "dr congo", "congo-kinshasa", "zaire"] },
  "188": { name: "Costa Rica", iso2: "CR", iso3: "CRI", aliases: [] },
  "384": { name: "Côte d'Ivoire", iso2: "CI", iso3: "CIV", aliases: ["cote d ivoire", "ivory coast"] },
  "191": { name: "Croatia", iso2: "HR", iso3: "HRV", aliases: [] },
  "192": { name: "Cuba", iso2: "CU", iso3: "CUB", aliases: [] },
  "196": { name: "Cyprus", iso2: "CY", iso3: "CYP", aliases: [] },
  "203": { name: "Czechia", iso2: "CZ", iso3: "CZE", aliases: ["czech republic"] },
  "208": { name: "Denmark", iso2: "DK", iso3: "DNK", aliases: [] },
  "262": { name: "Djibouti", iso2: "DJ", iso3: "DJI", aliases: [] },
  "212": { name: "Dominica", iso2: "DM", iso3: "DMA", aliases: [] },
  "214": { name: "Dominican Republic", iso2: "DO", iso3: "DOM", aliases: ["dominican rep."] },
  "218": { name: "Ecuador", iso2: "EC", iso3: "ECU", aliases: [] },
  "818": { name: "Egypt", iso2: "EG", iso3: "EGY", aliases: [] },
  "222": { name: "El Salvador", iso2: "SV", iso3: "SLV", aliases: [] },
  "226": { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", aliases: ["eq. guinea"] },
  "232": { name: "Eritrea", iso2: "ER", iso3: "ERI", aliases: [] },
  "233": { name: "Estonia", iso2: "EE", iso3: "EST", aliases: [] },
  "748": { name: "Eswatini", iso2: "SZ", iso3: "SWZ", aliases: ["swaziland"] },
  "231": { name: "Ethiopia", iso2: "ET", iso3: "ETH", aliases: [] },
  "242": { name: "Fiji", iso2: "FJ", iso3: "FJI", aliases: [] },
  "246": { name: "Finland", iso2: "FI", iso3: "FIN", aliases: [] },
  "250": { name: "France", iso2: "FR", iso3: "FRA", aliases: [] },
  "266": { name: "Gabon", iso2: "GA", iso3: "GAB", aliases: [] },
  "270": { name: "Gambia", iso2: "GM", iso3: "GMB", aliases: ["the gambia"] },
  "268": { name: "Georgia", iso2: "GE", iso3: "GEO", aliases: [] },
  "276": { name: "Germany", iso2: "DE", iso3: "DEU", aliases: [] },
  "288": { name: "Ghana", iso2: "GH", iso3: "GHA", aliases: [] },
  "300": { name: "Greece", iso2: "GR", iso3: "GRC", aliases: [] },
  "308": { name: "Grenada", iso2: "GD", iso3: "GRD", aliases: [] },
  "320": { name: "Guatemala", iso2: "GT", iso3: "GTM", aliases: [] },
  "324": { name: "Guinea", iso2: "GN", iso3: "GIN", aliases: [] },
  "624": { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", aliases: ["guinea bissau"] },
  "328": { name: "Guyana", iso2: "GY", iso3: "GUY", aliases: [] },
  "332": { name: "Haiti", iso2: "HT", iso3: "HTI", aliases: [] },
  "340": { name: "Honduras", iso2: "HN", iso3: "HND", aliases: [] },
  "348": { name: "Hungary", iso2: "HU", iso3: "HUN", aliases: [] },
  "352": { name: "Iceland", iso2: "IS", iso3: "ISL", aliases: [] },
  "356": { name: "India", iso2: "IN", iso3: "IND", aliases: ["bharat", "republic of india"] },
  "360": { name: "Indonesia", iso2: "ID", iso3: "IDN", aliases: [] },
  "364": { name: "Iran", iso2: "IR", iso3: "IRN", aliases: ["islamic republic of iran", "persia"] },
  "368": { name: "Iraq", iso2: "IQ", iso3: "IRQ", aliases: [] },
  "372": { name: "Ireland", iso2: "IE", iso3: "IRL", aliases: [] },
  "376": { name: "Israel", iso2: "IL", iso3: "ISR", aliases: [] },
  "380": { name: "Italy", iso2: "IT", iso3: "ITA", aliases: [] },
  "388": { name: "Jamaica", iso2: "JM", iso3: "JAM", aliases: [] },
  "392": { name: "Japan", iso2: "JP", iso3: "JPN", aliases: [] },
  "400": { name: "Jordan", iso2: "JO", iso3: "JOR", aliases: [] },
  "398": { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", aliases: [] },
  "404": { name: "Kenya", iso2: "KE", iso3: "KEN", aliases: [] },
  "296": { name: "Kiribati", iso2: "KI", iso3: "KIR", aliases: [] },
  "-99": { name: "Kosovo", iso2: "XK", iso3: "XKX", aliases: ["republic of kosovo"] },
  "414": { name: "Kuwait", iso2: "KW", iso3: "KWT", aliases: [] },
  "417": { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", aliases: ["kyrgyz republic"] },
  "418": { name: "Laos", iso2: "LA", iso3: "LAO", aliases: ["lao peoples democratic republic"] },
  "428": { name: "Latvia", iso2: "LV", iso3: "LVA", aliases: [] },
  "422": { name: "Lebanon", iso2: "LB", iso3: "LBN", aliases: [] },
  "426": { name: "Lesotho", iso2: "LS", iso3: "LSO", aliases: [] },
  "430": { name: "Liberia", iso2: "LR", iso3: "LBR", aliases: [] },
  "434": { name: "Libya", iso2: "LY", iso3: "LBY", aliases: [] },
  "438": { name: "Liechtenstein", iso2: "LI", iso3: "LIE", aliases: [] },
  "440": { name: "Lithuania", iso2: "LT", iso3: "LTU", aliases: [] },
  "442": { name: "Luxembourg", iso2: "LU", iso3: "LUX", aliases: [] },
  "450": { name: "Madagascar", iso2: "MG", iso3: "MDG", aliases: [] },
  "454": { name: "Malawi", iso2: "MW", iso3: "MWI", aliases: [] },
  "458": { name: "Malaysia", iso2: "MY", iso3: "MYS", aliases: [] },
  "462": { name: "Maldives", iso2: "MV", iso3: "MDV", aliases: [] },
  "466": { name: "Mali", iso2: "ML", iso3: "MLI", aliases: [] },
  "470": { name: "Malta", iso2: "MT", iso3: "MLT", aliases: [] },
  "584": { name: "Marshall Islands", iso2: "MH", iso3: "MHL", aliases: ["marshall is."] },
  "478": { name: "Mauritania", iso2: "MR", iso3: "MRT", aliases: [] },
  "480": { name: "Mauritius", iso2: "MU", iso3: "MUS", aliases: [] },
  "484": { name: "Mexico", iso2: "MX", iso3: "MEX", aliases: [] },
  "583": { name: "Micronesia", iso2: "FM", iso3: "FSM", aliases: ["federated states of micronesia"] },
  "498": { name: "Moldova", iso2: "MD", iso3: "MDA", aliases: [] },
  "492": { name: "Monaco", iso2: "MC", iso3: "MCO", aliases: [] },
  "496": { name: "Mongolia", iso2: "MN", iso3: "MNG", aliases: [] },
  "499": { name: "Montenegro", iso2: "ME", iso3: "MNE", aliases: [] },
  "504": { name: "Morocco", iso2: "MA", iso3: "MAR", aliases: [] },
  "508": { name: "Mozambique", iso2: "MZ", iso3: "MOZ", aliases: [] },
  "104": { name: "Myanmar", iso2: "MM", iso3: "MMR", aliases: ["burma"] },
  "516": { name: "Namibia", iso2: "NA", iso3: "NAM", aliases: [] },
  "520": { name: "Nauru", iso2: "NR", iso3: "NRU", aliases: [] },
  "524": { name: "Nepal", iso2: "NP", iso3: "NPL", aliases: [] },
  "528": { name: "Netherlands", iso2: "NL", iso3: "NLD", aliases: ["holland", "the netherlands"] },
  "554": { name: "New Zealand", iso2: "NZ", iso3: "NZL", aliases: [] },
  "558": { name: "Nicaragua", iso2: "NI", iso3: "NIC", aliases: [] },
  "562": { name: "Niger", iso2: "NE", iso3: "NER", aliases: [] },
  "566": { name: "Nigeria", iso2: "NG", iso3: "NGA", aliases: [] },
  "408": { name: "North Korea", iso2: "KP", iso3: "PRK", aliases: ["dprk", "democratic peoples republic of korea"] },
  "807": { name: "North Macedonia", iso2: "MK", iso3: "MKD", aliases: ["macedonia"] },
  "578": { name: "Norway", iso2: "NO", iso3: "NOR", aliases: [] },
  "512": { name: "Oman", iso2: "OM", iso3: "OMN", aliases: [] },
  "586": { name: "Pakistan", iso2: "PK", iso3: "PAK", aliases: [] },
  "585": { name: "Palau", iso2: "PW", iso3: "PLW", aliases: [] },
  "275": { name: "Palestine", iso2: "PS", iso3: "PSE", aliases: ["state of palestine"] },
  "591": { name: "Panama", iso2: "PA", iso3: "PAN", aliases: [] },
  "598": { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", aliases: ["png"] },
  "600": { name: "Paraguay", iso2: "PY", iso3: "PRY", aliases: [] },
  "604": { name: "Peru", iso2: "PE", iso3: "PER", aliases: [] },
  "608": { name: "Philippines", iso2: "PH", iso3: "PHL", aliases: ["the philippines"] },
  "616": { name: "Poland", iso2: "PL", iso3: "POL", aliases: [] },
  "620": { name: "Portugal", iso2: "PT", iso3: "PRT", aliases: [] },
  "634": { name: "Qatar", iso2: "QA", iso3: "QAT", aliases: [] },
  "642": { name: "Romania", iso2: "RO", iso3: "ROU", aliases: [] },
  "643": { name: "Russia", iso2: "RU", iso3: "RUS", aliases: ["russian federation"] },
  "646": { name: "Rwanda", iso2: "RW", iso3: "RWA", aliases: [] },
  "659": { name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", aliases: ["st. kitts and nevis", "st kitts", "saint kitts"] },
  "662": { name: "Saint Lucia", iso2: "LC", iso3: "LCA", aliases: ["st. lucia"] },
  "670": { name: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT", aliases: ["st. vin. and gren.", "st vincent", "saint vincent"] },
  "882": { name: "Samoa", iso2: "WS", iso3: "WSM", aliases: [] },
  "674": { name: "San Marino", iso2: "SM", iso3: "SMR", aliases: [] },
  "678": { name: "São Tomé and Príncipe", iso2: "ST", iso3: "STP", aliases: ["sao tome and principe", "sao tome"] },
  "682": { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", aliases: [] },
  "686": { name: "Senegal", iso2: "SN", iso3: "SEN", aliases: [] },
  "688": { name: "Serbia", iso2: "RS", iso3: "SRB", aliases: [] },
  "690": { name: "Seychelles", iso2: "SC", iso3: "SYC", aliases: [] },
  "694": { name: "Sierra Leone", iso2: "SL", iso3: "SLE", aliases: [] },
  "702": { name: "Singapore", iso2: "SG", iso3: "SGP", aliases: [] },
  "703": { name: "Slovakia", iso2: "SK", iso3: "SVK", aliases: ["slovak republic"] },
  "705": { name: "Slovenia", iso2: "SI", iso3: "SVN", aliases: [] },
  "090": { name: "Solomon Islands", iso2: "SB", iso3: "SLB", aliases: ["solomon is."] },
  "706": { name: "Somalia", iso2: "SO", iso3: "SOM", aliases: [] },
  "710": { name: "South Africa", iso2: "ZA", iso3: "ZAF", aliases: [] },
  "410": { name: "South Korea", iso2: "KR", iso3: "KOR", aliases: ["republic of korea", "korea"] },
  "728": { name: "South Sudan", iso2: "SS", iso3: "SSD", aliases: ["s. sudan"] },
  "724": { name: "Spain", iso2: "ES", iso3: "ESP", aliases: [] },
  "144": { name: "Sri Lanka", iso2: "LK", iso3: "LKA", aliases: [] },
  "729": { name: "Sudan", iso2: "SD", iso3: "SDN", aliases: [] },
  "740": { name: "Suriname", iso2: "SR", iso3: "SUR", aliases: [] },
  "752": { name: "Sweden", iso2: "SE", iso3: "SWE", aliases: [] },
  "756": { name: "Switzerland", iso2: "CH", iso3: "CHE", aliases: [] },
  "760": { name: "Syria", iso2: "SY", iso3: "SYR", aliases: ["syrian arab republic"] },
  "158": { name: "Taiwan", iso2: "TW", iso3: "TWN", aliases: ["republic of china", "chinese taipei"] },
  "762": { name: "Tajikistan", iso2: "TJ", iso3: "TJK", aliases: [] },
  "834": { name: "Tanzania", iso2: "TZ", iso3: "TZA", aliases: ["united republic of tanzania"] },
  "764": { name: "Thailand", iso2: "TH", iso3: "THA", aliases: [] },
  "626": { name: "Timor-Leste", iso2: "TL", iso3: "TLS", aliases: ["east timor", "timor leste"] },
  "768": { name: "Togo", iso2: "TG", iso3: "TGO", aliases: [] },
  "776": { name: "Tonga", iso2: "TO", iso3: "TON", aliases: [] },
  "780": { name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", aliases: ["trinidad"] },
  "788": { name: "Tunisia", iso2: "TN", iso3: "TUN", aliases: [] },
  "792": { name: "Turkey", iso2: "TR", iso3: "TUR", aliases: ["turkiye", "türkiye"] },
  "795": { name: "Turkmenistan", iso2: "TM", iso3: "TKM", aliases: [] },
  "800": { name: "Uganda", iso2: "UG", iso3: "UGA", aliases: [] },
  "804": { name: "Ukraine", iso2: "UA", iso3: "UKR", aliases: [] },
  "784": { name: "United Arab Emirates", iso2: "AE", iso3: "ARE", aliases: ["uae", "emirates"] },
  "826": { name: "United Kingdom", iso2: "GB", iso3: "GBR", aliases: ["uk", "britain", "great britain"] },
  "840": { name: "United States", iso2: "US", iso3: "USA", aliases: ["usa", "united states of america", "america", "us"] },
  "858": { name: "Uruguay", iso2: "UY", iso3: "URY", aliases: [] },
  "860": { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", aliases: [] },
  "548": { name: "Vanuatu", iso2: "VU", iso3: "VUT", aliases: [] },
  "336": { name: "Vatican City", iso2: "VA", iso3: "VAT", aliases: ["vatican", "holy see"] },
  "862": { name: "Venezuela", iso2: "VE", iso3: "VEN", aliases: [] },
  "704": { name: "Vietnam", iso2: "VN", iso3: "VNM", aliases: ["viet nam"] },
  "887": { name: "Yemen", iso2: "YE", iso3: "YEM", aliases: [] },
  "894": { name: "Zambia", iso2: "ZM", iso3: "ZMB", aliases: [] },
  "716": { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", aliases: [] },
}
